=== JerryGreen/lol/games_info_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "patch": {
      "type": "string"
    },
    "me": {
      "type": "string"
    },
    "vs": {
      "type": "string"
    },
    "lane": {
      "type": "string"
    },
    "rank": {
      "type": "string"
    },
    "replay_file": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "full_video": {
      "type": "string"
    },
    "promo_video": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "date",
    "patch",
    "me",
    "vs",
    "lane",
    "rank",
    "replay_file",
    "details",
    "full_video",
    "promo_video"
  ]
}

=== JerryGreen/lol/games_info/RU-292500952.json
{
  "id": "292500952",
  "date": "20200925",
  "patch": "10.19",
  "me": "Tryndamere",
  "vs": "Maokai",
  "lane": "top",
  "rank": "Gold IV",
  "replay_file": "replays/RU-292500952.rofl",
  "details": "https://matchhistory.ru.leagueoflegends.com/ru/#match-details/RU/292500952/202436939?tab=overview",
  "full_video": "https://youtu.be/L8iQBhVkG44",
  "promo_video": "https://youtu.be/0JOYZ2z3cR4"
}

=== JerryGreen/lol/games_info/RU-293040833.json
{
  "id": "293040833",
  "date": "20200927",
  "patch": "10.19",
  "me": "Tryndamere",
  "vs": "Darius",
  "lane": "top",
  "rank": "Gold IV",
  "replay_file": "replays/RU-293040833.rofl",
  "details": "https://matchhistory.ru.leagueoflegends.com/ru/#match-details/RU/293040833/202436939?tab=overview",
  "full_video": "https://youtu.be/lMIDCt6Ttgo",
  "promo_video": "https://youtu.be/0uuHaxHjTWY"
}
